version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t spareshop:latest .
      - run:
          name: Save Docker Image
          command: |
            mkdir -p docker-cache
            docker save -o docker-cache/spareshop.tar spareshop:latest
      - persist_to_workspace:
          root: .
          paths:
            - docker-cache

  test:
    docker:
      - image: docker:20.10.7
    steps:
      - attach_workspace:
          at: /workspace
      - setup_remote_docker
      - run:
          name: Load Docker Image
          command: |
            docker load -i /workspace/docker-cache/spareshop.tar
      - run:
          name: Test
          command: |
            docker run --rm -v "$(pwd):/app" spareshop:latest dotnet test

  deploy:
    docker:
      - image: docker:20.10.7
    steps:
      - attach_workspace:
          at: /workspace
      - setup_remote_docker
      - run:
          name: Load Docker Image
          command: |
            docker load -i /workspace/docker-cache/spareshop.tar
      - run:
          name: Deploy
          command: |
            # Your deployment script here

  tag-and-push:
    docker:
      - image: cimg/base:2023.08
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Load Docker Image
          command: |
            docker load -i docker-cache/spareshop.tar
      - run:
          name: Login to GHCR
          command: |
            echo "${GHCR_TOKEN}" | docker login ghcr.io -u "${GHCR_USERNAME}" --password-stdin
      - run:
          name: Tag and Push Docker Image
          command: |
            CALVER_TAG="$(date +"%Y.%m.%d")-$(echo "${CIRCLE_BRANCH}" | tr '/' '-')"
            docker tag spareshop:latest ghcr.io/${GHCR_USERNAME}/spareshop:${CALVER_TAG}
            docker push ghcr.io/${GHCR_USERNAME}/spareshop:${CALVER_TAG}
      - run:
          name: Tag Git Repository
          command: |
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"
            git tag "${CALVER_TAG}"
            git push origin "${CALVER_TAG}"

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
      - tag-and-push:
          requires:
            - test
